
const precedence = ["scissors", "paper", "rock", "scissors"];
let player, autogenerated, winner;
const result = document.getElementById("result");


function rock(){
    player="rock";  
}
function paper(){
    player="paper";  
}
function scissors(){
    player="scissors"; 
}
function generate(){
    autogenerated = precedence[Math.floor(Math.random*3)];  
}
function determine(){
    let result = document.getElementById("result");
    if(precedence.indexOf(player)>precedence.indexOf(autogenerated)){
        winner = "player";
    }
    else{
        winner = "computer";
    }
    if(winner == "player"){
        result.innerHTML = "You won!";
    }
    else{
        result.innerHTML = "You lost."
    }
}

const startButton = document.getElementById('start');
startButton.addEventListener('click', function() {
    play()
});
function play(){    
    document.getElementById("rock").addEventListener("click", function(){
        rock()
    });
    document.getElementById("paper").addEventListener("click", function(){
        paper()
    });
    document.getElementById("scissors").addEventListener("click", function(){
        scissors()
    });
    generate();
    determine();
}

document.addEventListener('keypress', function(event) {
    if (event.key === 'r' || event.key === 'R') {
    rock();
    } else if (event.key === 'p' || event.key === 'P') {
    paper();
    } else if (event.key === 's' || event.key === 'S') {
    scissors();
    }
});



document.getElementById("play-agn").addEventListener("click", function(){
    result.innerHTML="";
    play();
    });


result.addEventListener("change", function(){
    result.style.color="purple";
    result.style.fontSize=50; 
});